name: Build Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Private Notes Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: private.Dockerfile
          provenance: false
          push: true
          sbom: false
          tags: ghcr.io/ietf-tools/hedgedoc:latest

      - name: Build and push IETF Notes Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: notes.Dockerfile
          provenance: false
          push: true
          sbom: false
          tags: ghcr.io/ietf-tools/hedgedoc-notes:latest
